### ISSUE TITLE
异常格式化问题

### ISSUE THREAD

**Issue by loyating** [CatsSystem/CatCore#1]
PHP Warning:  var_export does not handle circular references in $vendor/cat-sys/cat-core/core/common/Formater.php on line 85
错误格式化有点儿问题。。。

**Comment by loyating** [comment]
api下的模块namespace   非顶级命名空间app  加载失败

**Comment by LinkedDestiny** [comment]
嗯，这里我今天会修复……

**Comment by LinkedDestiny** [comment]
已经修复
